---
title: "TidyTemplate"
date: 2021-03-02
output: html_output
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(ggtext)

```

# Load the weekly Data

Dowload the weekly data and make available in the `tt` object.

```{r Load}

tt <- tt_load("2021-03-02")

```


# Readme


```{r Readme, eval = interactive()}

tt

```


# Glimpse Data

Take an initial look at the format of the data available.

```{r Glimpse}

tt %>% 
  map(glimpse)

youtube <- tt$youtube

```

# Wrangle


```{r Wrangle}

superbowl_ads <- tt$youtube 

beer_ads <- superbowl_ads %>%
                add_count(brand, name = "total_commercials") %>%
                filter(brand == "Bud Light" | brand == "Budweiser") %>%
                rename(sex = use_sex, `Show product quickly` = show_product_quickly) %>%
                pivot_longer(cols = funny:sex, names_to = "category") %>%
                group_by(brand, category, value) %>%
                summarise(count = n(), 
                          perc = n()/total_commercials) %>%
    
                
                group_by(brand, category, perc) %>%
                filter(value == TRUE) %>% 
                summarise()
 
beer_ads$brand <- factor(beer_ads$brand, 
                         levels = c('Budweiser', 'Bud Light'))  

beer_ads$category <- str_to_upper(beer_ads$category)

#in case I use the tidytext
#https://juliasilge.com/blog/reorder-within/               
    
    

```


# Visualize


```{r Visualize}

beer_ads %>%
     ggplot(aes(fill = brand, y = perc, x = reorder(category, perc))) +
     geom_bar(position = "dodge", stat = "identity", width = 0.6) +
     coord_flip() +
     scale_y_continuous(labels = scales::percent) +
     scale_fill_manual(values = c("#f1000b", "#00A1E1")) +
   
     labs(x = "", y = "",
                 title = "Themes from <span style=color:#00A1E1;>Bud Light</span> and <span style=color:#f1000b>Budweiser</span><br>Super Bowl Commercials.<br>2000-2020.",
                 caption = "Data from FiveThirtyEight | Viz by Francisco GF") + 
     theme_void() +
     theme(
         plot.title = element_markdown(hjust = 0.5, size = 50, 
                                   face = "bold", lineheight = 0.3, 
                                   margin = margin(b = 1, unit = "cm")),
         plot.caption = element_text(size = 30, 
                                     margin = margin(t = 2, unit = "cm")),
         plot.margin=unit(c(2,2,.5,.5),"cm"),
         plot.background = element_rect(fill ="#d3d3d3"),
       
         
         axis.text = element_text(size = 35, hjust = 1),
         axis.title = element_text(size = 20),
         
         legend.position = "none"
   )
    
```

# Save Image

```{r}

ggsave("2021_03_02_superbowl.png", plot = last_plot(), 
       device = "png", path = here::here("Output", "2021_03_02_superbowl"),
       width = 25, height = 20)
```
