---
title: "TidyTemplate"
date: 2021-02-15
output: html_output
---

# TidyTuesday


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(showtext)

```

# Load the weekly Data

```{r Load}

tt <- tt_load("2021-02-16")

```


# Readme

```{r Readme, eval = interactive()}

tt

```


# Glimpse Data

Take an initial look at the format of the data available.

```{r Glimpse}

tt %>% 
  map(glimpse)

georgia <- tt$georgia_pop

```

#Wragnle

```{r}

georgia <- georgia %>%
            rename(COLORED = Colored, WHITE = White) %>%
            pivot_longer(!Year, names_to = "Race", values_to = "Percents")

```


# Visualize


```{r Visualize}

font_add_google("Public Sans", "Public Sans")
showtext_auto()

plot <- georgia %>%
          ggplot(aes( x = Year, y = Percents, group = Race)) +
            geom_line(aes(linetype = Race), size = 1) +
            scale_y_continuous(breaks = seq(0,100,5), trans = "reverse") +
            scale_x_continuous(breaks = seq(1790,1890,10)) +
            
            theme(plot.title = element_text(hjust = 0.5, size = 100,
                                            face = "bold", lineheight = 0.2),
                  plot.margin=unit(c(1,1,1,1),"cm"),
                  plot.background = element_rect(fill = "#ecdfd3"),
                  plot.caption = element_text(size = 60),
                  
                  panel.background = element_rect(fill = "#ecdfd3"),
                  panel.grid.major = element_line(color = "#dc143c", size = .4),
                  panel.grid.minor = element_blank(),
                  
                  axis.text = element_text(size = 70),
                  axis.title = element_text(size = 70),
                  
                  
                  legend.position = "bottom",
                  legend.title = element_blank(),
                  legend.text = element_text(size = 65),
                  legend.key.width = unit(3, "cm"),
                  legend.background = element_rect(fill = "transparent"),
                  legend.key = element_rect(colour = "transparent", 
                                            fill = "transparent"),
                  
                  
                  text = element_text(family = "Public Sans")) +
  
            labs(x = "", y = "PERCENTS",
                 title = "COMPARATIVE INCREASE OF WHITE AND COLORED \nPOPULATION OF GEORGIA.",
                 caption = "Data from #DuBoisChallenge | Francisco GF") +
  
            coord_flip(expand = FALSE)

plot

```

# Save Image


```{r}

ggsave(plot,
       filename = here::here("Output",
                             "2021_02_16_dubois",
                             "dubois.png"),
       dpi= 600,
       height = 12,
       width = 8)
```
