---
title: "TidyTemplate"
date: 2021-02-23
output: html_output
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)

```

# Load the weekly Data

```{r Load}

tt <- tt_load("2021-02-23")

```


# Readme

```{r Readme, eval = interactive()}

tt

```


# Glimpse Data

```{r Glimpse}

tt %>% 
  map(glimpse)

```

# Wrangle

```{r Wrangle}

employed <- tt$employed
earn <- tt$earn

employed_group <- employed %>%
                    mutate(industry = fct_collapse(industry,
                            `Other services` = c("Other services", 
                                                "Other services, except private households"),
                            `Wholesale and retail` = c("Retail trade", 
                                                        "Wholesale and retail trade",
                                                        "Wholesale trade"),
                            `Extractive industries` = c("Mining, quarrying, and oil and gas extraction"))) %>%
                    group_by(industry, race_gender, year) %>%
                    summarise(employ_n = sum(employ_n)) %>%
                    filter(race_gender != "TOTAL", 
                           race_gender != "Men",
                           race_gender != "Women",
                           industry != "Asian",
                           industry != "Black or African American")
                    

employed_2020 <- employed_group %>%
                    filter(year == 2020) %>%
                    arrange(employ_n) 

employed_2020$race_gender <- factor(employed_2020$race_gender, levels = c("Black or African American", "Asian", "White"))

```


# Visualize


```{r Visualize}

sysfonts::font_add_google(name = "Quantico","Quantico")
showtext::showtext_auto()

plot <- ggplot(employed_2020, aes(x= reorder(industry, employ_n), y = employ_n)) +
    geom_bar(aes(fill = fct_rev(race_gender)), stat = "identity", width = .6,
             position = position_stack(reverse = F)) +
    coord_flip() +
    scale_y_continuous(labels = scales::unit_format(unit = "M",
                                                    scale = 1e-6)) +
    scale_fill_manual(guide = guide_legend(reverse = T),
                      values=c("#dc143c","#f3b21a", "#00aa00")) +
    
    labs(x = "", y = "NUMBER OF EMPLOYEES",
                 title = "EMPLOYMENT BY INDUSTRY AND RACE.\n2020.",
                 caption = "Data from BLS | #DuBoisChallenge | Viz by Francisco GF") +
    
    theme(
        plot.title = element_text(hjust = 0.5, margin = margin(b = 2, unit = "cm"), size = 60, 
                                face = "bold", lineheight = 0.3),
        plot.caption = element_text(size = 25),
        plot.margin=unit(c(1,2,1,-.2),"cm"),
        plot.background = element_rect(fill = "#ffebcd"),
        panel.background = element_rect(fill = "#ffebcd"),
        panel.grid.major.y = element_blank(),
        
        axis.text = element_text(size = 35),
        axis.title = element_text(size = 20),
        
        legend.title = element_blank(),
        legend.position = "bottom",
        legend.text = element_text(size = 30),
        legend.background = element_rect(fill = "transparent"),
        legend.key = element_rect(colour = "transparent", 
                                    fill = "transparent"),
        
        text = element_text(family = "Quantico")
        )

plot
  
```

# Save Image

```{r}

ggsave("2021_06_23_BLS.png", plot = last_plot(), 
       device = "png", path = here::here("Output", "2021_06_23_BLS"),
       width = 9, height = 7)

```
