---
title: "TidyTemplate"
date: 2021-07-13
output: html_output
---

# TidyTuesday


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(hrbrthemes)

```

# Load the weekly Data

```{r Load}

tt <- tt_load("2021-07-13")

```


# Readme

```{r Readme, eval = interactive()}

tt

```


# Glimpse Data

```{r Glimpse}

tt %>% 
  map(glimpse)

```

# Wrangle



```{r Wrangle}

tidydata <- tt$scoobydoo %>%
                group_by(motive) %>%
                filter(motive != "NULL") %>%
                summarise(count = n()) %>%
                slice_max(order_by = count, n = 10)

```


# Visualize


```{r Visualize}

tidydata %>%
    ggplot(aes(x = count, y = reorder(motive, count))) +
               geom_col(width = .7,
                        color = "#b8be19", fill = "#b8be19") +
    
    
    theme_ft_rc() +
    theme(axis.title.x = element_text(size = 15)) +
    theme(axis.title.y = element_text(size = 15)) +

    
    labs(x = "Count", y = "Motive",
                 title = "Top 10 motives from Scooby Doo\nTV Episodes and Movies",
                 caption = "Data from Kaggle | Viz by Francisco GF") 

  
```

# Save Image


```{r}

ggsave("2021_07_13_scooby_doo.png", plot = last_plot(), 
       device = "png", path = here::here("Output", "2021_07_13_scooby_doo"),
       width = 9, height = 7)

```
